name: Check my PR puriizu
run-name: ${{ github.actor }} has created or updated a PR ğŸ‡âœ¨
on:
  pull_request:

jobs:
  inspect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Biome CLI
        uses: biomejs/setup-biome@main

      - name: Run Biome
        run: biome ci .
